// <auto-generated />
using CodeFirstMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstMVC.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    partial class EmployeeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeFirstMVC.Models.DeptInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("deptContact")
                        .HasColumnType("float");

                    b.Property<string>("deptEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deptManager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("deptNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CodeFirstMVC.Models.EmpInfo", b =>
                {
                    b.Property<int>("empNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empNo"), 1L, 1);

                    b.Property<int>("empDeptId")
                        .HasColumnType("int");

                    b.Property<string>("empDesigantion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("empIsPermenant")
                        .HasColumnType("bit");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("empSalary")
                        .HasColumnType("float");

                    b.HasKey("empNo");

                    b.HasIndex("empDeptId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CodeFirstMVC.Models.EmpInfo", b =>
                {
                    b.HasOne("CodeFirstMVC.Models.DeptInfo", "empDept")
                        .WithMany("empList")
                        .HasForeignKey("empDeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empDept");
                });

            modelBuilder.Entity("CodeFirstMVC.Models.DeptInfo", b =>
                {
                    b.Navigation("empList");
                });
#pragma warning restore 612, 618
        }
    }
}
